import java.util.Collection;
import java.util.ArrayList;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dany_
 */
public class ListaOrdini extends javax.swing.JFrame {

    /**
     * Creates new form Lista
     */
    public ListaOrdini(Collection<Object[]> lista, int idUtente) {
        this.lista=lista;
        this.idUtente=idUtente;
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titolo = new javax.swing.JLabel();
        pulsanteHome = new javax.swing.JButton();
        campoFiltro = new javax.swing.JTextField();
        pulsanteFiltra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        Object[] nomiColonne={"ID", "ID Farmacia", "Nome", "Quantità", "Data Consegna"};
        Object[][] matrice= new Object[this.lista.size()][nomiColonne.length];
        Object[] row=this.lista.toArray();
        Object[] riga=new Object[nomiColonne.length];
        this.pulsanteAnnulla=new javax.swing.JButton[this.lista.size()];
        this.pulsanteModifica=new javax.swing.JButton[this.lista.size()];

        for(int i=0; i<this.lista.size(); i++){
            for(int j=0; j<nomiColonne.length; j++){
                riga=(Object[])row[i];
                matrice[i][j]=riga[j];
            }
            this.pulsanteModifica[i]=new javax.swing.JButton("Modifica");
            this.pulsanteAnnulla[i]=new javax.swing.JButton("Annulla");
        }

        javax.swing.table.DefaultTableModel model= new javax.swing.table.DefaultTableModel(matrice, nomiColonne);
        model.addColumn("Modifica", this.pulsanteModifica);
        model.addColumn("Cancellazione", this.pulsanteAnnulla);


        tabella = new javax.swing.JTable(model);
        tabella.setDefaultRenderer(Object.class, new Renderer());
        tabella.setDefaultEditor(Object.class, new Editor(this));

        

        tabella.setRowHeight(30);
        


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        titolo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        titolo.setForeground(new java.awt.Color(0, 153, 153));
        titolo.setText("Lista Ordini");

        pulsanteHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        pulsanteHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home(evt);
            }
        });

        pulsanteFiltra.setText("Filtra");
        pulsanteFiltra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtra(evt);
            }
        });

        jScrollPane1.setViewportView(tabella);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(pulsanteHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(titolo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(campoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pulsanteFiltra)
                        .addGap(46, 46, 46))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(titolo)
                        .addComponent(pulsanteFiltra))
                    .addComponent(pulsanteHome, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selezioneRiga(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selezioneRiga
        this.rigaSelezionata=this.tabella.getSelectedRow();
    }//GEN-LAST:event_selezioneRiga

    private void filtra(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtra
        this.controlVisualizza=new ControlVisualizza(this.idUtente, "ordini");
        this.compila();
    }//GEN-LAST:event_filtra

    public void aggiorna(Collection<Object[]> lista){
        ListaOrdini listaNuova= new ListaOrdini(lista, this.idUtente);
        this.dispose();
    }

    public void compila(){
        this.controlVisualizza.setFiltro(this.getFiltro());
    }
    public String getFiltro(){
        return (String)this.campoFiltro.getText();
    }

    private void home(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home
        MenuPrincipale menu=new MenuPrincipale(this.idUtente);
        this.dispose();
    }//GEN-LAST:event_home

    public void modifica(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home
        Collection<Object> row= new ArrayList<Object>();
        for(int i=0;i<5;i++){
            row.add(this.tabella.getValueAt(this.tabella.getSelectedRow(), i));
        }
        this.controlModifica=new ControlModifica(this.idUtente, row);
        this.dispose();
    }//GEN-LAST:event_home

    public void annulla(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home
        Collection<Object> row= new ArrayList<Object>();
        for(int i=0;i<5;i++){
            row.add(this.tabella.getValueAt(this.tabella.getSelectedRow(), i));
        }
        this.controlModifica=new ControlModifica(this.idUtente, row);
        this.dispose();

    }//GEN-LAST:event_home

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoFiltro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pulsanteFiltra;
    private javax.swing.JButton pulsanteHome;
    private javax.swing.JTable tabella;
    private javax.swing.JLabel titolo;
    private Collection<Object[]> lista;
    private int idUtente;
    private javax.swing.JButton pulsanteModifica[];
    private javax.swing.JButton pulsanteAnnulla[];
    private int rigaSelezionata;
    private ControlVisualizza controlVisualizza;
    private ControlAnnulla controlAnnulla;
    private ControlModifica controlModifica;
    // End of variables declaration//GEN-END:variables
}
