import java.util.Collection;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Utente
 */
public class ModuloRiepilogo extends javax.swing.JFrame {
    

    /**
     * Creates new form ModuloRiepilogo
     */
    public ModuloRiepilogo(int idUtente, Collection<Object> riepilogo, Object control) {
        this.control=control;
        this.idUtente=idUtente;
        this.riepilogo=riepilogo;
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pulsanteAnnulla = new javax.swing.JButton();
        pulsanteConferma = new javax.swing.JButton();
        pulsanteHome = new javax.swing.JButton();


        Object[] nomiColonne;
        if(this.control instanceof ControlOrdina){
            nomiColonne= new Object[5];
            nomiColonne[0]="ID";
            nomiColonne[1]="Nome";
            nomiColonne[2]="Principio Attivo";
            nomiColonne[3]="Quantità";
            nomiColonne[4]="ID Farmacia";
        }else if(this.control instanceof ControlPrenota){
            nomiColonne= new Object[4];
            nomiColonne[0]="ID";
            nomiColonne[1]="Nome";
            nomiColonne[2]="Principio Attivo";
            nomiColonne[3]="Quantità";
        }else{
            if(this.idUtente/1000==1){
                nomiColonne= new Object[5];
                nomiColonne[0]="ID";
                nomiColonne[1]="ID Farmacia";
                nomiColonne[2]="Nome";
                nomiColonne[3]="Quantità";
                nomiColonne[4]="Data Consegna";
            }else{
                nomiColonne= new Object[4];
                nomiColonne[0]="ID";
                nomiColonne[1]="Nome";
                nomiColonne[2]="Quantità";
                nomiColonne[3]="Data Consegna";
            }
        }
        Object[][] matrice = new Object[1][nomiColonne.length];
        matrice[0]=this.riepilogo.toArray();

        jTable1= new javax.swing.JTable(matrice, nomiColonne);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("RIEPILOGO");

        jScrollPane1.setViewportView(jTable1);

        pulsanteAnnulla.setText("ANNULLA");
        pulsanteAnnulla.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pulsanteAnnulla.setBackground(new java.awt.Color(255, 0, 0));
        pulsanteAnnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulla(evt);
            }
        });

        pulsanteConferma.setText("CONFERMA");
        pulsanteConferma.setBackground(new java.awt.Color(0, 102, 0));
        pulsanteConferma.setFont(new java.awt.Font("Segoe UI", 0, 18));
        pulsanteConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conferma(evt);
            }
        });

        pulsanteHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        pulsanteHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(pulsanteAnnulla, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(pulsanteConferma)
                .addGap(179, 179, 179))
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pulsanteHome, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pulsanteHome))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pulsanteAnnulla)
                    .addComponent(pulsanteConferma))
                .addGap(197, 197, 197))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annulla(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteAnnullaActionPerformed
        ControlVisualizza controlVisualizza;
        if(this.control instanceof ControlPrenota){
            controlVisualizza= new ControlVisualizza(this.idUtente,"famraci");
        }else if(this.control instanceof ControlOrdina){
            controlVisualizza= new ControlVisualizza(this.idUtente,"magazzino");
        }else{
            if(this.idUtente/1000==1){
                controlVisualizza=new ControlVisualizza(this.idUtente, "ordini");
            }else{
                controlVisualizza=new ControlVisualizza(this.idUtente, "prenotazioni");
            }
        }
        controlVisualizza.run();
        this.dispose();
    }//GEN-LAST:event_pulsanteAnnullaActionPerformed

    private void conferma(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteConfermaActionPerformed
        if(this.control instanceof ControlOrdina){
            ((ControlOrdina)this.control).run();
        }
        if(this.control instanceof ControlPrenota){
            ((ControlPrenota)this.control).run();
        }
        if(this.control instanceof ControlModifica){
            ((ControlModifica)this.control).run();
        }
        if(this.control instanceof ControlAnnulla){
            ((ControlAnnulla)this.control).run();
        }
        this.dispose();
    }//GEN-LAST:event_pulsanteConfermaActionPerformed

    private void home(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteHomeActionPerformed
        MenuPrincipale menuPrincipale= new MenuPrincipale(this.idUtente);
        this.dispose();
    }//GEN-LAST:event_pulsanteHomeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton pulsanteAnnulla;
    private javax.swing.JButton pulsanteConferma;
    private javax.swing.JButton pulsanteHome;
    private int idUtente;
    private Object control;
    private Collection<Object> riepilogo;
    // End of variables declaration//GEN-END:variables
}
