import java.util.Collection;
import java.util.ArrayList;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dany_
 */
public class ModuloSoglia extends javax.swing.JFrame {

    /**
     * Creates new form ModuloSoglia
     */
    public ModuloSoglia(int idUtente, Collection<Object> datiRiepilogativi) {
        this.idUtente=idUtente;
        this.datiRiepilogativi=datiRiepilogativi;
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        pulsantePrenota = new javax.swing.JButton();
        pulsanteAnnulla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Avviso");

        Object[] nomiColonne= {"ID", "Nome", "Principio Attivo", "Quantità"};
        Object[][] matrice = new Object[1][nomiColonne.length];
        matrice[0]=datiRiepilogativi.toArray();

        jTable1= new javax.swing.JTable(matrice, nomiColonne);
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("La quantità residua del farmaco è inferiore a 10");

        pulsantePrenota.setBackground(new java.awt.Color(0, 102, 0));
        pulsantePrenota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pulsantePrenota.setForeground(new java.awt.Color(255, 255, 255));
        pulsantePrenota.setText("Prenota");
        pulsantePrenota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenota(evt);
            }
        });

        pulsanteAnnulla.setBackground(new java.awt.Color(255, 0, 0));
        pulsanteAnnulla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pulsanteAnnulla.setForeground(new java.awt.Color(255, 255, 255));
        pulsanteAnnulla.setText("Annulla");
        pulsanteAnnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulla(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(pulsanteAnnulla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pulsantePrenota)
                .addGap(192, 192, 192))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pulsantePrenota)
                    .addComponent(pulsanteAnnulla))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annulla(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulla
        ControlVisualizza controlVisualizza=new ControlVisualizza(this.idUtente, "farmaci");
        this.dispose();
    }//GEN-LAST:event_annulla

    private void prenota(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenota
        ((ArrayList<Object>)this.datiRiepilogativi).add(0, this.idUtente);
        this.controlPrenota=new ControlPrenota(this.datiRiepilogativi);
        this.dispose();
    }//GEN-LAST:event_prenota

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton pulsanteAnnulla;
    private javax.swing.JButton pulsantePrenota;
    private int idUtente;
    private ControlPrenota controlPrenota;
    private Collection<Object> datiRiepilogativi;
    // End of variables declaration//GEN-END:variables
}
